### ISSUE TITLE
error when Making performance prediction

### ISSUE THREAD

**Issue by liuqinfei** [PerfVec/PerfVec#3]
`
[root@node1 PerfVec]# cat CFG/rep_spectest_0124.py
# Data set configuration.
#dataset = 'Data_rep/spectest.pt' # 14 samples
dataset = 'res/prep_mm_cfg_LSTM_256_2_1222.pt' # 14 samples

test_start = 0
test_end = 14

cfg_num = 77
seq_length = 1
input_length = 256
tgt_length = 1

[root@node1 PerfVec]# python -m ML.test --no-save --cfg=rep_spectest_0124 --pred --checkpoints=checkpoints/LSTM_256_2_1222.pt "Predictor(cfg,bias=True)"
Load config rep_spectest_0124
/home/liuqinfei/PerfVec/PerfVec/ML/test.py:280: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  cp = torch.load(cp_name, map_location=torch.device('cpu'))
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/liuqinfei/PerfVec/PerfVec/ML/test.py", line 511, in <module>
    main()
  File "/home/liuqinfei/PerfVec/PerfVec/ML/test.py", line 507, in main
    test_main(0, args)
  File "/home/liuqinfei/PerfVec/PerfVec/ML/test.py", line 330, in test_main
    model = load_checkpoint(args.checkpoints, cfg, model_init, args.models[0])
  File "/home/liuqinfei/PerfVec/PerfVec/ML/test.py", line 296, in load_checkpoint
    model.load_state_dict(cp['model_state_dict'])
  File "/usr/local/lib64/python3.9/site-packages/torch/nn/modules/module.py", line 2584, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for Predictor:
        Missing key(s) in state_dict: "linear.bias".
        Unexpected key(s) in state_dict: "lstm.weight_ih_l0", "lstm.weight_hh_l0", "lstm.bias_ih_l0", "lstm.bias_hh_l0", "lstm.weight_ih_l1", "lstm.weight_hh_l1", "lstm.bias_ih_l1", "lstm.bias_hh_l1".

`

**Comment by liuqinfei** [comment]
My configuration parameters may be incorrect. Please help. Thanks. @lingda-li

**Comment by lingda-li** [comment]
Looks like you tried to load a checkpoint into a different model.

**Comment by liuqinfei** [comment]
> Looks like you tried to load a checkpoint into a different model.

OK, let me check one more time.

**Comment by liuqinfei** [comment]
Another question, it seems that gem5 can not simulate I/O, so it's hard to predict storage application performance. Do you have some suggestions or plans about that?

**Comment by lingda-li** [comment]
I think gem5 simulates some IO but not sure about how detailed it is. You can potentially implement/plugin detailed IO models in gem5.

**Comment by liuqinfei** [comment]
Hi, Another question. From your paper "Learning Generalizable Program and Architecture Representations for Performance Modeling". ti = Ri * M. Ri is the representation of the ith instruction and M is the target microarchitecture representation, So, how did you  map the two vector? Does the mapping have a physical meaning?

**Comment by lingda-li** [comment]
Not sure what you meant by mapping. Ri*M is a standard dot product compuation, and both are learned so it is hard to figure out a physical meaning for them.

**Comment by liuqinfei** [comment]
> Not sure what you meant by mapping. Ri*M is a standard dot product compuation, and both are learned so it is hard to figure out a physical meaning for them.

Thanks. In fact, i already run and predict a performance result from your code example "mm 8 8 8". But, what is the hardware configurations for the result? Where can i change the configurations of hardware architecture?

**Comment by lingda-li** [comment]
The hardware configuration is the gem5 configuration that you simulated with. You can change gem5 configuration, and will need to have/train a corresponding microarchitecture representation for performance prediction.
